name: deploy-cagl.ar
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}
on:
  push:
    branches:
      - master

env:
  APP_PATH: "/var/www/html/cagl.ar"
  USERNAME: "user"
  SERVER_IP: "208.97.140.85"
  SERVER_URL: "cagl.ar"
  SSH_KEY: ${{ secrets.CAGLAR }}

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: prepare
        run: |
          mkdir ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/$SERVER_URL
          chmod 600 ~/.ssh/$SERVER_URL
          cat >>~/.ssh/config <<END
          Host $SERVER_URL
            HostName $SERVER_URL
            User $USERNAME
            IdentityFile ~/.ssh/$SERVER_URL
            StrictHostKeyChecking no
          END

      - name: deploy
        run:
          scp -r ./* $USERNAME@$SERVER_URL:$APP_PATH
